routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/contact', 'HomeController@contact');
Route::post('/contact', 'HomeController@contact_save');

Route::get('/page/{slug}', 'PageController@get_page');
Route::get('/news/', 'NewsController@get_news_list');
Route::get('/news/{id}', 'NewsController@get_post');
Route::get('lang/{locale}', 'LanguageController@index');
Route::get('/employee/{slug}', 'EmployeeController@get_employees');
Route::get('/rate/{news_id}/{rate}', 'RateController@make_rate');
Route::get('/get-news-comments/{news_id}', 'CommentController@get_news_comments');
Route::post('/add-comment', 'CommentController@add_comment');
Route::post('/add-course-message', 'Course_messageController@add_message');


//
Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');


Auth::routes(['register' => false]);
Route::group(['prefix'=>'admin','middleware'=>'auth'], function() {
    Route::get('/home', 'HomeController@home');
    Route::resource('users', 'UserController');
    Route::resource('news', 'NewsController');
    Route::resource('pages', 'PageController');
    Route::resource('employees', 'EmployeeController');
    Route::resource('contactMessages', 'Contact_messageController');
});

Route::resource('comments', 'CommentController');

Route::resource('menus', 'MenuController');

Route::resource('courses', 'CourseController');

Route::resource('courseMessages', 'Course_messageController');

app/Models/Contact_message.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class Contact_message
 * @package App\Models
 * @version February 20, 2020, 8:00 pm UTC
 *
 * @property string name
 * @property string email
 * @property string message
 * @property string read
 */
class Contact_message extends Model
{

    public $table = 'contact_messages';
    



    public $fillable = [
        'name',
        'email',
        'message',
        'read'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'email' => 'string',
        'message' => 'string',
        'read' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/Contact_messageController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\Contact_messageDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateContact_messageRequest;
use App\Http\Requests\UpdateContact_messageRequest;
use App\Models\Contact_message;
use App\Repositories\Contact_messageRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class Contact_messageController extends AppBaseController
{
    /** @var  Contact_messageRepository */
    private $contactMessageRepository;

    public function __construct(Contact_messageRepository $contactMessageRepo)
    {
        $this->contactMessageRepository = $contactMessageRepo;
    }

    /**
     * Display a listing of the Contact_message.
     *
     * @param Contact_messageDataTable $contactMessageDataTable
     * @return Response
     */
    public function index(Contact_messageDataTable $contactMessageDataTable)
    {
        return $contactMessageDataTable->render('contact_messages.index');
    }

    /**
     * Show the form for creating a new Contact_message.
     *
     * @return Response
     */
    public function create()
    {
        return view('contact_messages.create');
    }

    /**
     * Store a newly created Contact_message in storage.
     *
     * @param CreateContact_messageRequest $request
     *
     * @return Response
     */
    public function store(CreateContact_messageRequest $request)
    {
        $input = $request->all();

        $contactMessage = $this->contactMessageRepository->create($input);

        echo "success";
    }

    /**
     * Display the specified Contact_message.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $contactMessage = $this->contactMessageRepository->find($id);

        if (empty($contactMessage)) {
            Flash::error('Contact Message not found');

            return redirect(route('contactMessages.index'));
        }

        return view('contact_messages.show')->with('contactMessage', $contactMessage);
    }

    /**
     * Show the form for editing the specified Contact_message.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $message = Contact_message::find($id);
        $message->read = "O'qilgan";
        $message->save();

        Flash::success('Xabar o\'qilgan deb belgilandi.');

        return redirect(route('contactMessages.index'));
    }


    /**
     * Remove the specified Contact_message from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $contactMessage = $this->contactMessageRepository->find($id);

        if (empty($contactMessage)) {
            Flash::error('Contact Message not found');

            return redirect(route('contactMessages.index'));
        }

        $this->contactMessageRepository->delete($id);

        Flash::success('Xabar o\'chirildi.');

        return redirect(route('contactMessages.index'));
    }
}

resources/views/contact_messages/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('contactMessages.index') !!}">Xabarlar</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Contact Message</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'contactMessages.store']) !!}

                                   @include('contact_messages.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/contact_messages/datatables_actions.blade.php
{!! Form::open(['route' => ['contactMessages.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('contactMessages.show', $id) }}" class='btn btn-outline-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('contactMessages.edit', $id) }}" class='btn btn-outline-info'>
       <i class="fa fa-bookmark"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-outline-danger',
        'onclick' => "return confirm('Ishinchinhiz komilmi?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/contact_messages/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('contactMessages.index') !!}">Contact Message</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Contact Message</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($contactMessage, ['route' => ['contactMessages.update', $contactMessage->id], 'method' => 'patch']) !!}

                              @include('contact_messages.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/contact_messages/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Message Field -->
<div class="form-group col-sm-6">
    {!! Form::label('message', 'Message:') !!}
    {!! Form::text('message', null, ['class' => 'form-control']) !!}
</div>

<!-- Read Field -->
<div class="form-group col-sm-6">
    {!! Form::label('read', 'Read:') !!}
    {!! Form::text('read', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('contactMessages.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/contact_messages/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Xabarlar</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Xabarlar
                         </div>
                         <div class="card-body">
                             @include('contact_messages.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/contact_messages/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('contactMessages.index') }}">Xabarlar</a>
            </li>
            <li class="breadcrumb-item active">Ko'rish</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Xabar</strong>
                                  <a href="{{ route('contactMessages.index') }}" class="btn btn-outline-primary">Orqaga</a>
                             </div>
                             <div class="card-body">
                                 @include('contact_messages.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/contact_messages/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $contactMessage->id }}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Ismi:') !!}
    <p>{{ $contactMessage->name }}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{{ $contactMessage->email }}</p>
</div>

<!-- Message Field -->
<div class="form-group">
    {!! Form::label('message', 'Xabar:') !!}
    <p>{{ $contactMessage->message }}</p>
</div>

<!-- Read Field -->
<div class="form-group">
    {!! Form::label('read', 'O\'qilganligi:') !!}
    <p>{{ $contactMessage->read }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Xabar yaratilgan vaqt:') !!}
    <p>{{ $contactMessage->created_at }}</p>
</div>

resources/views/contact_messages/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection