routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/contact', 'HomeController@contact');
Route::post('/contact', 'HomeController@contact_save');

Route::get('/page/{slug}', 'PageController@get_page');
Route::get('/news/', 'NewsController@get_news_list');
Route::get('/news/{id}', 'NewsController@get_post');
Route::get('lang/{locale}', 'LanguageController@index');
Route::get('/employee/{slug}', 'EmployeeController@get_employees');
Route::get('/rate/{news_id}/{rate}', 'RateController@make_rate');
Route::get('/get-news-comments/{news_id}', 'CommentController@get_news_comments');
Route::post('/add-comment', 'CommentController@add_comment');
Route::post('/add-course-message', 'Course_messageController@add_message');


//
Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');


Auth::routes(['register' => false]);
Route::group(['prefix'=>'admin','middleware'=>'auth'], function() {
    Route::get('/home', 'HomeController@home');
    Route::resource('users', 'UserController');
    Route::resource('news', 'NewsController');
    Route::resource('pages', 'PageController');
    Route::resource('employees', 'EmployeeController');
    Route::resource('contactMessages', 'Contact_messageController');
});

Route::resource('comments', 'CommentController');

Route::resource('menus', 'MenuController');

Route::resource('courses', 'CourseController');

Route::resource('courseMessages', 'Course_messageController');

app/Models/Course_message.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class Course_message
 * @package App\Models
 * @version February 27, 2020, 10:25 am UTC
 *
 * @property integer course_id
 * @property string name
 * @property string email
 * @property string phone
 */
class Course_message extends Model
{

    public $table = 'course_messages';
    



    public $fillable = [
        'course_id',
        'name',
        'email',
        'phone'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'course_id' => 'integer',
        'name' => 'string',
        'email' => 'string',
        'phone' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/Course_messageController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\Course_messageDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateCourse_messageRequest;
use App\Http\Requests\UpdateCourse_messageRequest;
use App\Models\Course_message;
use App\Repositories\Course_messageRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Response;

class Course_messageController extends AppBaseController
{
    /** @var  Course_messageRepository */
    private $courseMessageRepository;

    public function __construct(Course_messageRepository $courseMessageRepo)
    {
        $this->courseMessageRepository = $courseMessageRepo;
    }

    /**
     * Display a listing of the Course_message.
     *
     * @param Course_messageDataTable $courseMessageDataTable
     * @return Response
     */
    public function index(Course_messageDataTable $courseMessageDataTable)
    {
        return $courseMessageDataTable->render('course_messages.index');
    }

    /**
     * Show the form for creating a new Course_message.
     *
     * @return Response
     */
    public function create()
    {
        return view('course_messages.create');
    }

    /**
     * Store a newly created Course_message in storage.
     *
     * @param CreateCourse_messageRequest $request
     *
     * @return Response
     */
    public function store(CreateCourse_messageRequest $request)
    {
        $input = $request->all();

        $courseMessage = $this->courseMessageRepository->create($input);

        Flash::success('Course Message saved successfully.');

        return redirect(route('courseMessages.index'));
    }

    /**
     * Display the specified Course_message.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $courseMessage = $this->courseMessageRepository->find($id);

        if (empty($courseMessage)) {
            Flash::error('Course Message not found');

            return redirect(route('courseMessages.index'));
        }

        return view('course_messages.show')->with('courseMessage', $courseMessage);
    }

    /**
     * Show the form for editing the specified Course_message.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $courseMessage = $this->courseMessageRepository->find($id);

        if (empty($courseMessage)) {
            Flash::error('Course Message not found');

            return redirect(route('courseMessages.index'));
        }

        return view('course_messages.edit')->with('courseMessage', $courseMessage);
    }

    /**
     * Update the specified Course_message in storage.
     *
     * @param  int              $id
     * @param UpdateCourse_messageRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCourse_messageRequest $request)
    {
        $courseMessage = $this->courseMessageRepository->find($id);

        if (empty($courseMessage)) {
            Flash::error('Course Message not found');

            return redirect(route('courseMessages.index'));
        }

        $courseMessage = $this->courseMessageRepository->update($request->all(), $id);

        Flash::success('Course Message updated successfully.');

        return redirect(route('courseMessages.index'));
    }

    /**
     * Remove the specified Course_message from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $courseMessage = $this->courseMessageRepository->find($id);

        if (empty($courseMessage)) {
            Flash::error('Course Message not found');

            return redirect(route('courseMessages.index'));
        }

        $this->courseMessageRepository->delete($id);

        Flash::success('Course Message deleted successfully.');

        return redirect(route('courseMessages.index'));
    }

    public function add_message(Request $request)
    {
        $newmsg = new Course_message();
        $newmsg->fill($request->all());
        $newmsg->save();
    }
}

resources/views/course_messages/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('courseMessages.index') !!}">Course Message</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Course Message</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'courseMessages.store']) !!}

                                   @include('course_messages.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/course_messages/datatables_actions.blade.php
{!! Form::open(['route' => ['courseMessages.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('courseMessages.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('courseMessages.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Ishonchingiz komilmi?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/course_messages/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('courseMessages.index') !!}">Course Message</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Course Message</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($courseMessage, ['route' => ['courseMessages.update', $courseMessage->id], 'method' => 'patch']) !!}

                              @include('course_messages.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/course_messages/fields.blade.php
<!-- Course Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('course_id', 'Course Id:') !!}
    {!! Form::text('course_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('courseMessages.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/course_messages/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Kurslarga qatnashmoqchi bo'lganlar</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Kurslarga qatnashmoqchi bo'lganlar
                         </div>
                         <div class="card-body">
                             @include('course_messages.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/course_messages/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('courseMessages.index') }}">Course Message</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('courseMessages.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('course_messages.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/course_messages/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $courseMessage->id }}</p>
</div>

<!-- Course Id Field -->
<div class="form-group">
    {!! Form::label('course_id', 'Course Id:') !!}
    <p>{{ $courseMessage->course_id }}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $courseMessage->name }}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{{ $courseMessage->email }}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{{ $courseMessage->phone }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $courseMessage->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $courseMessage->updated_at }}</p>
</div>

resources/views/course_messages/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection