routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/contact', 'HomeController@contact');
Route::post('/contact', 'HomeController@contact_save');

Route::get('/page/{slug}', 'PageController@get_page');
Route::get('/news/', 'NewsController@get_news_list');
Route::get('/news/{id}', 'NewsController@get_post');
Route::get('lang/{locale}', 'LanguageController@index');
Route::get('/employee/{slug}', 'EmployeeController@get_employees');
Route::get('/rate/{news_id}/{rate}', 'RateController@make_rate');
Route::get('/get-news-comments/{news_id}', 'CommentController@get_news_comments');
Route::post('/add-comment', 'CommentController@add_comment');
Route::post('/add-course-message', 'Course_messageController@add_message');


//
Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');


Auth::routes(['register' => false]);
Route::group(['prefix'=>'admin','middleware'=>'auth'], function() {
    Route::get('/home', 'HomeController@home');
    Route::resource('users', 'UserController');
    Route::resource('news', 'NewsController');
    Route::resource('pages', 'PageController');
    Route::resource('employees', 'EmployeeController');
    Route::resource('contactMessages', 'Contact_messageController');
});

Route::resource('comments', 'CommentController');

Route::resource('menus', 'MenuController');

Route::resource('courses', 'CourseController');

Route::resource('courseMessages', 'Course_messageController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Sayt boshqaruv paneli</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 4.1.1 -->
    <link rel="stylesheet" href="{{asset('/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/bootstrap-datetimepicker.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('css/coreui.min.css')}}">
    <link rel="icon" href="{{asset('images/logo.ico')}}" type="image/x-icon" />
    <!-- Ionicons -->
    <link href="{{asset('css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/simple-line-icons.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/flag-icon.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/datatables.min.css')}}"/>
    <link rel="stylesheet" href="{{asset('css/custom-data-table.css')}}">
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
<header class="app-header navbar">
    <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">
        <img class="navbar-brand-full" src="http://infyom.com/images/logo/blue_logo_150x150.jpg" width="30" height="30"
             alt="InfyOm Logo">
        <img class="navbar-brand-minimized" src="http://infyom.com/images/logo/blue_logo_150x150.jpg" width="30"
             height="30" alt="Infyom Logo">
    </a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
        <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" style="margin-right: 10px" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false">
                {!! Auth::user()->name !!}
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header text-center">
                    <strong>Account</strong>
                </div>
                <a class="dropdown-item" href="{!! url('/logout') !!}" class="btn btn-default btn-flat"
                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="fa fa-lock"></i>Chiqish
                </a>
                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </div>
        </li>
    </ul>
</header>

<div class="app-body">
    @include('layouts.sidebar')
    <main class="main">
        @yield('content')
    </main>
</div>
<footer class="app-footer">
    <div>
        <span>&copy; 2020 Adminstrator panel.</span>
    </div>
</footer>
</body>
<!-- jQuery 3.1.1 -->
<script src="{{asset('js/jquery-3.3.1.min.js')}}"></script>
<script src="{{asset('js/popper.min.js')}}"></script>
<script src="{{asset('js/bootstrap.min.js')}}"></script>
<script src="{{asset('js/moment.min.js')}}"></script>
<script src="{{asset('js/bootstrap-datetimepicker.min.js')}}"></script>
<script src="{{asset('js/coreui.min.js')}}"></script>
<script src="{{asset('js/sweetalert.js')}}"></script>
<script src="{{asset('js/tinymce/tinymce.min.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
<script>
    tinymce.init({
        force_br_newlines : true,
        force_p_newlines : false,
        forced_root_block : '',
        selector: "textarea",theme: "modern",//width: 680,height: 300,
        plugins: [
            "advlist autolink link image lists charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking",
            "table contextmenu directionality emoticons paste textcolor responsivefilemanager code"
        ],
        toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect",
        toolbar2: "| responsivefilemanager | link unlink anchor | image media | forecolor backcolor  | print preview code ",
        image_advtab: true ,

        external_filemanager_path:"/filemanager/",
        filemanager_title:"Responsive Filemanager" ,
        external_plugins: { "filemanager" : "/filemanager/plugin.min.js"}
    });
    $('.iframe-btn').fancybox({
        'width'		: 600,
        'height'	: 600,
        'type'		: 'iframe',
        'autoScale'    	: false
    });
</script>
@yield('scripts')

</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
<li class="nav-item {{ Request::is('news*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('news.index') }}">
        <i class="nav-icon fa fa-newspaper-o"></i>
        <span>Yangiliklar</span>
    </a>
</li>
<li class="nav-item {{ Request::is('contactMessages*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('contactMessages.index') }}">
        <i class="nav-icon fa fa-envelope"></i>
        <span>Xabarlar</span>
    </a>
</li>
<li class="nav-item {{ Request::is('pages*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('pages.index') }}">
        <i class="nav-icon fa fa-book"></i>
        <span>Sahifalar</span>
    </a>
</li>
{{--<li class="nav-item {{ Request::is('employees*') ? 'active' : '' }}">--}}
    {{--<a class="nav-link" href="{{ route('employees.index') }}">--}}
        {{--<i class="nav-icon fa fa-users"></i>--}}
        {{--<span>Hodimlar</span>--}}
    {{--</a>--}}
{{--</li>--}}
<li class="nav-item {{ Request::is('comments*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('comments.index') }}">
        <i class="nav-icon fa fa-comment"></i>
        <span>Komentariyalar</span>
    </a>
</li>
<li class="nav-item {{ Request::is('menus*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('menus.index') }}">
        <i class="nav-icon fa fa-navicon"></i>
        <span>Menyular</span>
    </a>
</li>
<li class="nav-item {{ Request::is('users*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('users.index') }}">
        <i class="nav-icon fa fa-user-secret"></i>
        <span>Administratorlar</span>
    </a>
</li>
<li class="nav-item {{ Request::is('courses*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('courses.index') }}">
        <i class="nav-icon fa fa-star"></i>
        <span>Kurslar</span>
    </a>
</li>
<li class="nav-item {{ Request::is('courseMessages*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('courseMessages.index') }}">
        <i class="nav-icon fa fa-envelope-o"></i>
        <span>Kurs xatlari</span>
    </a>
</li>

resources/views/layouts/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            @include('layouts.menu')
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>