routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/contact', 'HomeController@contact');
Route::post('/contact', 'HomeController@contact_save');

Route::get('/page/{slug}', 'PageController@get_page');
Route::get('/news/', 'NewsController@get_news_list');
Route::get('/news/{id}', 'NewsController@get_post');
Route::get('lang/{locale}', 'LanguageController@index');
Route::get('/employee/{slug}', 'EmployeeController@get_employees');
Route::get('/rate/{news_id}/{rate}', 'RateController@make_rate');
Route::get('/get-news-comments/{news_id}', 'CommentController@get_news_comments');
Route::post('/add-comment', 'CommentController@add_comment');
Route::post('/add-course-message', 'Course_messageController@add_message');


//
Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');


Auth::routes(['register' => false]);
Route::group(['prefix'=>'admin','middleware'=>'auth'], function() {
    Route::get('/home', 'HomeController@home');
    Route::resource('users', 'UserController');
    Route::resource('news', 'NewsController');
    Route::resource('pages', 'PageController');
    Route::resource('employees', 'EmployeeController');
    Route::resource('contactMessages', 'Contact_messageController');
});

Route::resource('comments', 'CommentController');

Route::resource('menus', 'MenuController');

Route::resource('courses', 'CourseController');

Route::resource('courseMessages', 'Course_messageController');

resources/views/pages/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('pages.index') !!}">Sahifalar</a>
      </li>
      <li class="breadcrumb-item active">Qo'shish</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Sahifa qo'shish</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'pages.store']) !!}

                                   @include('pages.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/pages/datatables_actions.blade.php
{!! Form::open(['route' => ['pages.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('pages.show', $id) }}" class='btn btn-outline-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('pages.edit', $id) }}" class='btn btn-outline-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-outline-danger',
        'onclick' => "return confirm('Ishinchinhiz komilmi?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/pages/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('pages.index') !!}">Sahifalar</a>
          </li>
          <li class="breadcrumb-item active">O'zgartirish</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Sahifani o'zgartirish</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($page, ['route' => ['pages.update', $page->id], 'method' => 'patch']) !!}

                              @include('pages.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/pages/fields.blade.php
<!-- Slug Field -->
<div class="form-group col-sm-12">
    {!! Form::label('slug', 'Menyu:') !!}
    {!! Form::select('slug', $menus, null, ['class' => 'form-control']) !!}
</div>

<!-- Title Uz Field -->
<div class="form-group col-sm-12">
    {!! Form::label('title_uz', 'Sarlovha Uz:') !!}
    {!! Form::text('title_uz', null, ['class' => 'form-control']) !!}
</div>

<!-- Title Ru Field -->
<div class="form-group col-sm-12">
    {!! Form::label('title_ru', 'Sarlovha Ru:') !!}
    {!! Form::text('title_ru', null, ['class' => 'form-control']) !!}
</div>

<!-- Title En Field -->
<div class="form-group col-sm-12">
    {!! Form::label('title_en', 'Sarlovha En:') !!}
    {!! Form::text('title_en', null, ['class' => 'form-control']) !!}
</div>

<!-- Content Uz Field -->
<div class="form-group col-sm-12">
    {!! Form::label('content_uz', 'Text Uz:') !!}
    {!! Form::textarea('content_uz', null, ['class' => 'form-control']) !!}
</div>

<!-- Content Ru Field -->
<div class="form-group col-sm-12">
    {!! Form::label('content_ru', 'Text Ru:') !!}
    {!! Form::textarea('content_ru', null, ['class' => 'form-control']) !!}
</div>

<!-- Content En Field -->
<div class="form-group col-sm-12">
    {!! Form::label('content_en', 'Text En:') !!}
    {!! Form::textarea('content_en', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Saqlash', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('pages.index') }}" class="btn btn-danger">Bekor qilish</a>
</div>

resources/views/pages/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Sahifalar</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Sahifalar
                         </div>
                         <div class="card-body">
                             @include('pages.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/pages/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('pages.index') }}">Sahifalar</a>
            </li>
            <li class="breadcrumb-item active">Ko'rish</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Ko'rish</strong>
                                  <a href="{{ route('pages.index') }}" class="btn btn-outline-primary">Orqaga</a>
                             </div>
                             <div class="card-body">
                                 @include('pages.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/pages/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $page->id }}</p>
</div>

<!-- Slug Field -->
<div class="form-group">
    {!! Form::label('slug', 'URL:') !!}
    <p>{{ $page->slug }}</p>
</div>

<!-- Title Uz Field -->
<div class="form-group">
    {!! Form::label('title_uz', 'Sarlovha Uz:') !!}
    <p>{{ $page->title_uz }}</p>
</div>

<!-- Title Ru Field -->
<div class="form-group">
    {!! Form::label('title_ru', 'Sarlovha Ru:') !!}
    <p>{{ $page->title_ru }}</p>
</div>

<!-- Title En Field -->
<div class="form-group">
    {!! Form::label('title_en', 'Sarlovha En:') !!}
    <p>{{ $page->title_en }}</p>
</div>

<!-- Content Uz Field -->
<div class="form-group">
    {!! Form::label('content_uz', 'Text Uz:') !!}
    <p>{{ $page->content_uz }}</p>
</div>

<!-- Content Ru Field -->
<div class="form-group">
    {!! Form::label('content_ru', 'Text Ru:') !!}
    <p>{{ $page->content_ru }}</p>
</div>

<!-- Content En Field -->
<div class="form-group">
    {!! Form::label('content_en', 'Text En:') !!}
    <p>{{ $page->content_en }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Qo\'shilgan vaqti:') !!}
    <p>{{ $page->created_at }}</p>
</div>

resources/views/pages/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection